title: statman-stopwatch
description: simple high res stopwatch for node.js

google_analytics: G-9EZ6F8520W

remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme

show_downloads: false

# github:
#   zip_url: http://example.com/download.zip
#   another_url: another value
